Task_1_2 was completed
Artemonchik/OOP-course pull request #3
Opened 2020-10-16 19:01 UTC by Artemonchik

2020-10-22 17:53 UTC, vlitomsk requested changes
Замечания нужно исправить.

2020-10-22 17:53 UTC, vlitomsk commented on Task_1_2/src/main/java/SubstringFinder.java
> +    public static ArrayList<Integer> findSubstring(InputStreamReader file, char[] searchParam) throws IOException {
Вам про off_t рассказывали? Обрати внимание на тип возвращаемого смещения. Что, если файл будет 100 гигов?

2020-10-22 17:53 UTC, vlitomsk commented on Task_1_2/src/main/java/SubstringFinder.java
> +    public static ArrayList<Integer> findSubstring(InputStreamReader file, char[] searchParam) throws IOException {
InputStreamReader можно ослабить до InputStream-а

2020-10-22 17:53 UTC, vlitomsk commented on Task_1_2/src/main/java/SubstringFinder.java
> +    public static ArrayList<Integer> findSubstring(InputStreamReader file, char[] searchParam) throws IOException {
Добавь валидацию входных параметров -- например, с null-ами ты не сможешь работать. Под это есть NullPointerException.

2020-10-22 17:53 UTC, vlitomsk commented on Task_1_2/src/main/java/SubstringFinder.java
> +                indexes.add(initialPosInFile + i);
В случае когда:
1. нашли вхождение в конце буфера
2. сдвинули данные в буфере и прочитали новые
3. запустили поиск на следующей итерации большого цикла
входная строка будет обнаружена дважды -- первый раз -- когда она была в конце буфера, второй раз -- когда она была в начале буфера, после сдвига.

2020-10-22 17:53 UTC, vlitomsk commented on Task_1_2/src/main/java/SubstringFinder.java
> +                buf[paramLen + result] = 0;
А смысл? Мы так наоборот в конце потока сможем найти не ту строку, которую просили. А ту, которую просили, с последним символом, равным нулю.
(Строки в джяве не являются нуль-терминированными, 0 вполне себе законный символ)

2020-10-22 17:53 UTC, vlitomsk commented on Task_1_2/src/main/java/SubstringFinder.java
> +                        continue m;
подозреваю, что работает неправильно, и вместо этого надо было break поставить, чтобы завершить цикл на j и перейти к следующей итерации по i.
И вообще метки в джяве используются крайне редко в случае крайней необходимости, а в повседневном коде вызывают удивление.

2020-10-22 17:53 UTC, vlitomsk commented on Task_1_2/src/main/java/SubstringFinder.java
> +                break;
google code style и скобки

2020-10-28 19:46 UTC, Artemonchik commented on Task_1_2/src/main/java/SubstringFinder.java
> +    public static ArrayList<Integer> findSubstring(InputStreamReader file, char[] searchParam) throws IOException {
> InputStreamReader можно ослабить до InputStream-а

Так начнутся же проблемы с кодировкой?

2020-10-28 19:49 UTC, Artemonchik commented on Task_1_2/src/main/java/SubstringFinder.java
> +                indexes.add(initialPosInFile + i);
Мы ищем строку с начиная с символа, который находится не дальше половины буфера, поэтому два раза считать не будет (тесты же как - то проходит)

2020-10-28 19:55 UTC, Artemonchik commented on Task_1_2/src/main/java/SubstringFinder.java
> +                buf[paramLen + result] = 0;
Поставил нелегальный символ

2020-10-30 08:47 UTC, vlitomsk requested changes
А если не utf-8 ? Пользователь такой функции может удивиться.

2020-10-30 08:47 UTC, vlitomsk commented on Task_1_2/src/main/java/SubstringFinder.java
> +                buf[paramLen + result] = '\u0080'; // illegal character in UTF-8 encoding
А если кодировка другая у потока будет?

2020-10-30 09:30 UTC, Artemonchik commented on Task_1_2/src/main/java/SubstringFinder.java
> +                buf[paramLen + result] = '\u0080'; // illegal character in UTF-8 encoding
По заданию просто utf-8, я и сразу отталкивался от этого

2020-11-01 11:51 UTC, npanin1 commented on Task_1_2/src/main/java/SubstringFinder.java
> +                buf[paramLen + result] = '\u0080'; // illegal character in UTF-8 encoding
Всем джавистам приветики

2020-11-19 19:15 UTC, vlitomsk approved these changes
Принято

2020-11-19 19:16 UTC, merged